### ISSUE TITLE
AnchorFile missing

### ISSUE THREAD

**Issue by jakeju92** [speshowBUAA/PointPillars_mmdet_secfpn#1]
Hi,

I cannot find the anchor text file in this repo. 
<img width="664" alt="image" src="https://user-images.githubusercontent.com/5748897/165242969-700ff401-2abb-4d06-9a9d-8b4e9d32df4d.png">
Could you please upload the file pls! Thanks!

**Comment by speshowBUAA** [comment]
Updated! Thx for watching

**Comment by jakeju92** [comment]
Cool! Thanks for your speedy reply!
